name: norminette

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  check-norminette:
    name: Norminette
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: norminette
        uses: 42School/norminette@3.3.58
        with:
          args: '-RCheckForbiddenSourceHeader'
