name: norminette

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: update apt-get
        run: sudo apt-get update
      - name: install norminette
        run: pip install norminette==3.3.58
      - name: checkout
        uses: actions/checkout@v4
      - name: run norminette
        run: |
          norminette | grep -ve 'OK!' -ve 'Notice'
